### ISSUE TITLE
after start nothing happens

### ISSUE THREAD

**Issue by JamesOlvertone** [farjs/farjs#51]
after install and "farjs" nothing happens, no windows appear.

Tested with node v8, v17 (nodebrew-versions) on ubuntu 22.

**Comment by viktor-podzigun** [comment]
Thanks for reporting the issue, will take a look to it shortly.

Btw, the minimum supported Node.js version is v12

**Comment by viktor-podzigun** [comment]
Please, try the latest release (`v0.7.4`), the issue should be fixed.

**Comment by JamesOlvertone** [comment]
Tested on node v18.7.0: works!
